--Calcular a quantidade vendida por cliente
SELECT
NF.CPF,
NF.DATA_VENDA,
INF.QUANTIDADE
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO;

--Calcular a quantidade vendida por cliente por mes
SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY');

--visualizando a tabela de clientes
SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;

--Juntando o resultado da query da tabela de clientes com o resultado da consulta anterior, mostrando o cadastro e a quantidade total
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA AS PREVISAO_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,

(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS DENTRO OU ALEM DO PREVISTO'
ELSE 'VENDAS ABAIXO DO PREVISTO' END) AS RESULTADO

FROM TABELA_DE_CLIENTES TC

INNER JOIN
(SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')) TV
ON TV.CPF = TC.CPF;


-- Ranking das vendas totais por sabor no ano de 2016
SELECT
TP.SABOR,
EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL

FROM TABELA_DE_PRODUTOS TP

INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO

INNER JOIN
NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO

WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016

GROUP BY 
TP.SABOR,
EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;